import { useState } from "react";
import { Address, DELIVERY_STATUSES, DeliveryStatus, Order, OrderLine, Product, STATUS_LABEL, VALID_BLOCKS, addressLabel } from "./domain";

type StatusHandler=(id:string,status:DeliveryStatus)=>void;
type RouteStartHandler=(addressId:string,enabled:boolean)=>void;
type OrderUpdateHandler=(id:string,patch:Partial<Pick<Order,"customerName"|"phone"|"items"|"notes"|"paymentStatus"|"lineItems"|"total">>)=>void;

export function OrderDetails({order,address,products,routeStartAddressId,showRouteStartPrompt,onStatus,onRouteStart,onUpdate,onDelete,onClose}:{order:Order;address?:Address;products:Product[];routeStartAddressId?:string;showRouteStartPrompt:boolean;onStatus:StatusHandler;onRouteStart:RouteStartHandler;onUpdate:OrderUpdateHandler;onDelete:(id:string)=>void;onClose:()=>void}){
  const [editing,setEditing]=useState(false);
  return <>
    <div className="panel-title"><div><p>Order details</p><h2>{order.customerName}</h2></div><div className="sheet-actions"><span className={`status-pill ${order.status}`}>{STATUS_LABEL[order.status]}</span><button className="sheet-close" onClick={onClose} aria-label="Close order details">×</button></div></div>
    {editing?<OrderEditor order={order} products={products} onSave={(patch)=>{onUpdate(order.id,patch);setEditing(false);}} onCancel={()=>setEditing(false)}/>:<div className="details"><p><strong>Address</strong>{address?addressLabel(address):"Address missing"}</p><p><strong>Order</strong>{order.items}</p>{order.total!==undefined&&order.total>0&&<p><strong>Total</strong>₱{order.total.toFixed(2)} · {order.paymentStatus==="paid"?"Paid":"Unpaid"}</p>}{order.phone&&<p><strong>Contact</strong>{order.phone}</p>}{order.notes&&<p><strong>Notes</strong>{order.notes}</p>}</div>}
    {!editing&&<div className="manage-actions"><button onClick={()=>setEditing(true)}>Edit order</button><button className="danger" onClick={()=>onDelete(order.id)}>Delete</button></div>}
    <StatusSelect order={order} address={address} routeStartAddressId={routeStartAddressId} showRouteStartPrompt={showRouteStartPrompt} onStatus={onStatus} onRouteStart={onRouteStart} className="status-control"/>
  </>;
}

export function AddressDetails({address,orders,products,routeStartAddressId,pendingRouteStartOrderId,onStatus,onRouteStart,onUpdateOrder,onDeleteOrder,onUpdateAddress,onDeleteAddress,onAdd,onClose}:{address:Address;orders:Order[];products:Product[];routeStartAddressId?:string;pendingRouteStartOrderId:string|null;onStatus:StatusHandler;onRouteStart:RouteStartHandler;onUpdateOrder:OrderUpdateHandler;onDeleteOrder:(id:string)=>void;onUpdateAddress:(id:string,patch:Pick<Address,"phase"|"block"|"lot"|"customerName"|"phone">)=>boolean;onDeleteAddress:(id:string)=>void;onAdd:()=>void;onClose:()=>void}){
  const [editingAddress,setEditingAddress]=useState(false);const [editingOrderId,setEditingOrderId]=useState<string|null>(null);
  const activeOrders=orders.filter((order)=>order.status!=="delivered"||order.id===pendingRouteStartOrderId);
  return <div className="address-details">
    <div className="panel-title"><div><p>Saved address</p><h2>{addressLabel(address)}</h2></div><div className="sheet-actions"><span className="address-order-count">{activeOrders.length} active</span><button className="sheet-close" onClick={onClose} aria-label="Close address details">×</button></div></div>
    {editingAddress?<AddressEditor address={address} onSave={(patch)=>{if(onUpdateAddress(address.id,patch))setEditingAddress(false);}} onCancel={()=>setEditingAddress(false)}/>:<div className="manage-actions"><button onClick={()=>setEditingAddress(true)}>Edit address</button><button className="danger" onClick={()=>onDeleteAddress(address.id)}>Delete</button></div>}
    <div className="address-orders">{activeOrders.map(order=><article key={order.id}>{editingOrderId===order.id?<OrderEditor order={order} products={products} onSave={(patch)=>{onUpdateOrder(order.id,patch);setEditingOrderId(null);}} onCancel={()=>setEditingOrderId(null)}/>:<><div className="address-order-heading"><div><strong>{order.customerName}</strong><small>{order.items}</small></div><span className={`status-pill ${order.status}`}>{STATUS_LABEL[order.status]}</span></div>{order.total!==undefined&&order.total>0&&<small className="address-order-meta">₱{order.total.toFixed(2)} · {order.paymentStatus==="paid"?"Paid":"Unpaid"}</small>}{order.phone&&<small className="address-order-meta">Contact: {order.phone}</small>}{order.notes&&<small className="address-order-meta">{order.notes}</small>}<div className="manage-actions compact"><button onClick={()=>setEditingOrderId(order.id)}>Edit</button><button className="danger" onClick={()=>onDeleteOrder(order.id)}>Delete</button></div><StatusSelect order={order} address={address} routeStartAddressId={routeStartAddressId} showRouteStartPrompt={order.id===pendingRouteStartOrderId} onStatus={onStatus} onRouteStart={onRouteStart}/></>}</article>)}{!activeOrders.length&&<p className="no-address-orders">No active orders at this address.</p>}</div>
    <button className="primary-button" onClick={onAdd}>+ Add another order</button>
  </div>;
}

function OrderEditor({order,products,onSave,onCancel}:{order:Order;products:Product[];onSave:(patch:Partial<Order>)=>void;onCancel:()=>void}){
  const [name,setName]=useState(order.customerName),[phone,setPhone]=useState(order.phone),[items,setItems]=useState(order.items),[notes,setNotes]=useState(order.notes),[payment,setPayment]=useState<"unpaid"|"paid">(order.paymentStatus??"unpaid");
  const [lines,setLines]=useState<OrderLine[]>(order.lineItems??[]),[productId,setProductId]=useState(""),[quantity,setQuantity]=useState("1");
  const total=lines.reduce((sum,line)=>sum+line.quantity*line.unitPrice,0);
  const addLine=()=>{const product=products.find((item)=>item.id===productId),count=Number(quantity);if(!product||!Number.isInteger(count)||count<1)return;setLines((current)=>[...current,{productId:product.id,name:product.name,quantity:count,unitPrice:product.price}]);setProductId("");setQuantity("1");};
  const savedItems=lines.length?lines.map((line)=>`${line.quantity} × ${line.name}`).join(", "):items.trim();
  return <div className="management-form"><label>Customer<input value={name} onChange={(event)=>setName(event.target.value)}/></label><label>Phone<input value={phone} onChange={(event)=>setPhone(event.target.value)}/></label><label className="full">Order description<input value={items} disabled={lines.length>0} onChange={(event)=>setItems(event.target.value)} placeholder={lines.length?"Generated from products":"Order details"}/></label><div className="order-line-editor full"><strong>Products</strong>{lines.map((line,index)=><div className="editable-order-line" key={`${line.productId??line.name}:${index}`}><span>{line.quantity} × {line.name}<small>₱{(line.quantity*line.unitPrice).toFixed(2)}</small></span><button onClick={()=>setLines((current)=>current.filter((_,lineIndex)=>lineIndex!==index))}>Remove</button></div>)}<div className="order-line-picker"><select aria-label="Product" value={productId} onChange={(event)=>setProductId(event.target.value)}><option value="">Choose product</option>{products.filter((product)=>product.active||lines.some((line)=>line.productId===product.id)).map((product)=><option value={product.id} key={product.id}>{product.name} — ₱{product.price.toFixed(2)}</option>)}</select><input aria-label="Quantity" type="number" min="1" inputMode="numeric" value={quantity} onChange={(event)=>setQuantity(event.target.value.replace(/\D/g,""))}/><button disabled={!productId||Number(quantity)<1} onClick={addLine}>Add</button></div><strong className="order-edit-total">Total: ₱{(lines.length?total:Number(order.total)||0).toFixed(2)}</strong></div><label>Payment<select value={payment} onChange={(event)=>setPayment(event.target.value as "unpaid"|"paid")}><option value="unpaid">Unpaid</option><option value="paid">Paid</option></select></label><label className="full">Notes<textarea value={notes} onChange={(event)=>setNotes(event.target.value)}/></label><div className="form-actions full"><button onClick={onCancel}>Cancel</button><button className="primary-button" disabled={!name.trim()||!savedItems} onClick={()=>onSave({customerName:name.trim(),phone:phone.trim(),items:savedItems,notes:notes.trim(),paymentStatus:payment,lineItems:lines,total:lines.length?total:Number(order.total)||0})}>Save changes</button></div></div>;
}

function AddressEditor({address,onSave,onCancel}:{address:Address;onSave:(patch:Pick<Address,"phase"|"block"|"lot"|"customerName"|"phone">)=>void;onCancel:()=>void}){
  const [phase,setPhase]=useState<1|2>(address.phase),[block,setBlock]=useState(address.block),[lot,setLot]=useState(String(address.lot)),[name,setName]=useState(address.customerName??""),[phone,setPhone]=useState(address.phone??"");
  return <div className="management-form"><label>Phase<select value={phase} onChange={(event)=>{const next=Number(event.target.value) as 1|2;setPhase(next);setBlock(VALID_BLOCKS[next][0]);}}><option value="1">Phase 1</option><option value="2">Phase 2</option></select></label><label>Block<select value={block} onChange={(event)=>setBlock(Number(event.target.value))}>{VALID_BLOCKS[phase].map((value)=><option key={value} value={value}>{value}</option>)}</select></label><label>Lot<input type="number" min="1" value={lot} onChange={(event)=>setLot(event.target.value)}/></label><label>Customer<input value={name} onChange={(event)=>setName(event.target.value)}/></label><label className="full">Phone<input value={phone} onChange={(event)=>setPhone(event.target.value)}/></label><div className="form-actions full"><button onClick={onCancel}>Cancel</button><button className="primary-button" disabled={!Number.isInteger(Number(lot))||Number(lot)<1} onClick={()=>onSave({phase,block,lot:Number(lot),customerName:name.trim(),phone:phone.trim()})}>Save address</button></div></div>;
}

function StatusSelect({order,address,routeStartAddressId,showRouteStartPrompt,onStatus,onRouteStart,className}:{order:Order;address?:Address;routeStartAddressId?:string;showRouteStartPrompt:boolean;onStatus:StatusHandler;onRouteStart:RouteStartHandler;className?:string}){
  return <div className={className}><label>Update status<select value={order.status} onChange={event=>onStatus(order.id,event.target.value as DeliveryStatus)}>{DELIVERY_STATUSES.map(value=><option key={value} value={value}>{STATUS_LABEL[value]}</option>)}</select></label>{showRouteStartPrompt&&order.status==="delivered"&&address&&<label className="route-start-option"><input type="checkbox" checked={routeStartAddressId===address.id} onChange={(event)=>onRouteStart(address.id,event.target.checked)}/><span><strong>Continue from this location</strong><small>Use this address—not home—as the next route’s starting point.</small></span></label>}</div>;
}
